[package]
name = "keen_solver"
version = "0.1.0"
edition = "2021"
default-run = "keen_solver"

[profile.release]
debug = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.3"
pest_derive = "2.7.3"
union-find = "0.4.1"
